//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Officework.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Userdetail1
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Name is required")]
        [RegularExpression("^[A-Za-z ]*$",ErrorMessage ="Use letters only please")]
        [StringLength(10,MinimumLength =3,ErrorMessage ="Input must contain between 3 to 10 letters")]

        public string Name { get; set; }
        [Required(ErrorMessage = "Phone no is required")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Use numbers only please")]
        public string Phone_no { get; set; }
        public string Location { get; set; }
    }
}
